### ISSUE TITLE
Having trouble getting the docker demos up running on OSX

### ISSUE THREAD

**Issue by dlethin** [pvdissel/talk-jenkins-jobdsl#1] opened 2015-02-23 15:12 UTC
The work you've done setting this repo up and sharing your experience is fantastic.   Unfortunately, I'm running into an issue starting it up and its most likely due to me being a novice docker user.  I'd had some success in the past with boot2docker on OSX but for some reason its not working for me.

It tried 2 different ways to get this up and running -- The first without prefacing dockerCmd with sudo and the 2nd time with sudo.  I get different error message for each:

Here is the output when I run without modifying dockerCmd in jenkins shell script you wrote:

[note I'm only trying to startup the first demo]

<pre>
#bash -x ./demo-1 start "demos/01-few-jobs/" 8081
...
>> Copying plugins to Jenkins...
>> Pinning plugins to not be overridden by Jenkins' defaults...
>> Make Jobs directory accessable for current user...
>> Creating [Seed] job...
Starting [demo-1-8081] container...
docker --log-level="debug" run -d -p 8081:8080 --name demo-1-8081 -u root  -v /Users/dlethin/bld/github/talk-jenkins-jobdsl/.containers/demo-1-8081/jenkins-home:/var/jenkins_home -v /Users/dlethin/bld/github/talk-jenkins-jobdsl/.containers/demo-1-8081/jenkins-root:/root -v /Users/dlethin/bld/github/talk-jenkins-jobdsl/demos/01-few-jobs/:/source:ro jenkins:1.580.2
Unable to find image 'jenkins:1.580.2' locally
511136ea3c5a: Pull complete 
848d84b4b2ab: Pull complete 
71d9d77ae89e: Pull complete 
34664741b33f: Pull complete 
bd8bd16075a0: Pull complete 
c15d04694341: Pull complete 
5e97c669e8ad: Pull complete 
b872be1ed4e2: Pull complete 
dc840aab2066: Pull complete 
adc3c45c3240: Pull complete 
af766fe5dc2c: Pull complete 
e7ef9888cb99: Pull complete 
a6e79208f6c7: Pull complete 
19fa2105ca6e: Pull complete 
793fec17483e: Pull complete 
7148a8699c1b: Pull complete 
b3c5c6dad599: Pull complete 
06014de83093: Pull complete 
5bfbd5bbce29: Pull complete 
0199cbd51953: Pull complete 
41001f44325b: Pull complete 
jenkins:1.580.2: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.
Status: Downloaded newer image for jenkins:1.580.2
FATA[0318] Error response from daemon: Could not create local directory '/Users/dlethin/bld/github/talk-jenkins-jobdsl/.containers/demo-1-8081/jenkins-root' for bind mount: mkdir /Users/dlethin/bld/github/talk-jenkins-jobdsl/.containers/demo-1-8081/jenkins-root: protocol error! 
!! An error occurred while starting container [demo-1-8081]

</pre>

Here is the output when I modify DockerCmd with sudo:

<pre>

Downloaded: 52 files, 89M in 1m 0s (1.49 MB/s)
+ [[ 0 -ne 0 ]]
+ cp -f /Users/dlethin/bld/github/talk-jenkins-jobdsl/plugin-urls.txt /Users/dlethin/bld/github/talk-jenkins-jobdsl/.jenkins-plugins/plugin-urls.txt
+ removeDir /Users/dlethin/bld/github/talk-jenkins-jobdsl/.containers/demo-1-8081/jenkins-home/plugins
+ set -o xtrace
+ sudo rm -r /Users/dlethin/bld/github/talk-jenkins-jobdsl/.containers/demo-1-8081/jenkins-home/plugins
rm: /Users/dlethin/bld/github/talk-jenkins-jobdsl/.containers/demo-1-8081/jenkins-home/plugins: No such file or directory
+ set +o xtrace
>> Copying plugins to Jenkins...
>> Pinning plugins to not be overridden by Jenkins' defaults...
>> Make Jobs directory accessable for current user...
>> Creating [Seed] job...
Starting [demo-1-8081] container...
sudo docker --log-level="debug" run -d -p 8081:8080 --name demo-1-8081 -u root  -v /Users/dlethin/bld/github/talk-jenkins-jobdsl/.containers/demo-1-8081/jenkins-home:/var/jenkins_home -v /Users/dlethin/bld/github/talk-jenkins-jobdsl/.containers/demo-1-8081/jenkins-root:/root -v /Users/dlethin/bld/github/talk-jenkins-jobdsl/demos/01-few-jobs/:/source:ro jenkins:1.580.2
FATA[0000] Post http:///var/run/docker.sock/v1.17/containers/create?name=demo-1-8081: dial unix /var/run/docker.sock: no such file or directory. Are you trying to connect to a TLS-enabled daemon without TLS? 
!! An error occurred while starting container [demo-1-8081]

</pre>

Here are my env variables related to docker:

<pre>
sh-3.2$ env|grep DOCKER
DOCKER_HOST=tcp://192.168.59.106:2376
DOCKER_TLS_VERIFY=1
DOCKER_CERT_PATH=/Users/dlethin/.boot2docker/certs/boot2docker-vm
sh-3.2$ boot2docker ip
192.168.59.106
</pre>

This is what my dockerCmd looks like in Jenkins:

<pre>
# need to run as sudo on osx
#dockerCmd='docker --log-level="debug"'
dockerCmd='sudo docker --log-level="debug"'
#dockerCmd='docker --log-level="debug"'

</pre>

Is there something obvious I'm doing wrong?

Thanks.

Doug Lethin

**Comment by dlethin** [comment] 2015-02-23 15:26
I thought the issue might be that sudo does not preserve my env variable, so I changed my dockerCmd to looks like this, but it still did not seem to have any change in output.

<pre>
# need to run as sudo on osx
#dockerCmd='docker --log-level="debug"'
#dockerCmd='sudo docker --log-level="debug"'
dockerCmd="sudo DOCKER_HOST=$DOCKER_HOST DOCKER_CERT_PATH=$DOCKER_CERT_PATH DOCKER_TLS_VERIFY=1 docker"
#dockerCmd='docker --log-level="debug"'
</pre>

**Comment by pvdissel** [comment] 2015-02-23 17:54
From the output of where you run with sudo, the error

> dial unix /var/run/docker.sock: no such file or directory

sounds like boot2docker is not started or initialized.

While the output from when you run without sudo, it correctly downloads the
image, so boot2docker must have been started :-)
The following error indicates it's failing to create a directory:

> Status: Downloaded newer image for jenkins:1.580.2
> FATA[0318] Error response from daemon: Could not create local directory
> '/Users/dlethin/bld/github/talk-jenkins-jobdsl/.containers/demo-1-8081/jenkins-root' for bind mount: mkdir
> /Users/dlethin/bld/github/talk-jenkins-jobdsl/.containers/demo-1-8081/jenkins-root: protocol error!
> !! An error occurred while starting container [demo-1-8081]

And therefor it can't start the container.
I do not have a Mac, so I can't reproduce anything. Maybe you can find a
hint when looking for boot2docker and "protocol error"?

If you haven't found a solution by Thursday, I will ask a Mac user at work
to try it. (Thursday as I'm on a training till then)

If you find a solution, I hope to hear it :-) Otherwise, I hope to to find
a Mac user at work to try it out.

**Comment by dlethin** [comment] 2015-02-23 21:54
I've had some _manual_ success, but haven't quite got things right yet.

First,  it appears we do not need to run docker with sudo on macOX.  That is, I'm making the most progress not doing so.

Second, it seems that I need to have $jenkinsUserHomeDir (and not owned by root) created before I start docker.

With that, I can get past my docker failure above -- however, the script just keeps polling the docker log waiting for jenkins to come up, but it fails with an error.

It seems the last thing I need to do to get this up and running is to chown ownership of $jenkinsUserHomeDir to myself and not root and things appear to work -- that is I can got to jenkins then in a browser running out of the container.  Whether or not it did everything correct remains to be seen.

Will have to continue to plug away at this and see if I can make the right changes in the script to have this automated and working on OSX.

Thanks again.

**Comment by pvdissel** [comment] 2015-02-23 22:52
Ah that's a good one. Because boot2docker actually runs docker within a
virtualbox, the directories should not be made by root. In that case, we
can set a variable with a prefix command when using boot2docker. Add sudo
in case of using boot2docker, and use the prefix variable instead of the
sudo directly. We can then set the prefix value in the globals*something
function, where all variables get initialized.

I think that should work

**Comment by pvdissel** [comment] 2015-02-24 09:30
@dlethin can you try the following script? It leaves out the `sudo` when boot2docker is found:
https://gist.github.com/pvdissel/efe99cb84d93b8ad721c

**Comment by dlethin** [comment] 2015-02-24 12:31
Last night I had made some modifications similar to yours and ran into the behavior where starts to work, but Jenkins just hangs starting up.  The browser is stuck with the usual message -- "Please wait while Jenkins is getting ready to work", the demo start script is looping/sleeping waiting for docker log to produce "Jenkins is fully up and running".  There appears to be no errors in the docker log -- here are the contents that I can see.  Just seeing the last line stuck at "INFO: Started initialization"

<pre>
sh-3.2$ docker logs demo-1-8081
/usr/share/jenkins/ref/init.groovy.d/tcp-slave-angent-port.groovy
 /usr/share/jenkins/ref/init.groovy.d/tcp-slave-angent-port.groovy -> init.groovy.d/tcp-slave-angent-port.groovy
copy init.groovy.d/tcp-slave-angent-port.groovy to JENKINS_HOME
Running from: /usr/share/jenkins/jenkins.war
webroot: EnvVars.masterEnvVars.get("JENKINS_HOME")
Feb 23, 2015 10:43:35 PM winstone.Logger logInternal
INFO: Beginning extraction from war file
Feb 23, 2015 10:43:40 PM org.eclipse.jetty.util.log.JavaUtilLog info
INFO: jetty-winstone-2.8
Feb 23, 2015 10:43:53 PM org.eclipse.jetty.util.log.JavaUtilLog info
INFO: NO JSP Support for , did not find org.apache.jasper.servlet.JspServlet
Jenkins home directory: /var/jenkins_home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
Feb 23, 2015 10:43:54 PM org.eclipse.jetty.util.log.JavaUtilLog info
INFO: Started SelectChannelConnector@0.0.0.0:8080
Feb 23, 2015 10:43:54 PM winstone.Logger logInternal
INFO: Winstone Servlet Engine v2.0 running: controlPort=disabled
Feb 23, 2015 10:43:55 PM jenkins.InitReactorRunner$1 onAttained
INFO: Started initialization
</pre>

This behavior is consistent when I try your modified version of the script (thank you, btw)

I guess I'm going to next look for clues related to jenkins startup hanging.

Cheers.

**Comment by dlethin** [comment] 2015-02-24 17:11
So I looked our real jenkins installation log file to see what the next step in the initialization sequence is.  Looks like it is supposed to be something like this:

<pre>
INFO: NO JSP Support for , did not find org.apache.jasper.servlet.JspServlet
Jenkins home directory: /home/jenkins found at: System.getProperty("JENKINS_HOME")
Feb 18, 2015 2:29:16 AM org.eclipse.jetty.util.log.JavaUtilLog info
INFO: Started SelectChannelConnector@localhost:8090
Feb 18, 2015 2:29:16 AM winstone.Logger logInternal
INFO: Winstone Servlet Engine v2.0 running: controlPort=disabled
Feb 18, 2015 2:29:30 AM jenkins.InitReactorRunner$1 onAttained
INFO: Started initialization
Feb 18, 2015 2:29:49 AM hudson.ClassicPluginStrategy createPluginWrapper
INFO: Plugin create-fingerprint.jpi is disabled
Feb 18, 2015 2:29:56 AM jenkins.InitReactorRunner$1 onAttained
INFO: Listed all plugins
Feb 18, 2015 2:30:00 AM org.jvnet.hudson.plugins.m2release.M2ReleaseBuildWrapper$DescriptorImpl 
...
</pre>

So, it seems to be something related to the initialization/loading of the plugins that is hanging.  Unfortunately, since this is running in a container, I don't think I can ssh to the container so that I can get a java stack trace and see what might be hanging.

Perhaps there is some form of permission issue going on with the volumes I'm mounting -- this is the closes link I could find to a clue, but still not sure if its relevant --

https://github.com/cloudbees/jenkins-ci.org-docker/issues/25

Perhaps its a umask issue?  I set my umask to 0000 to be overly generous.

Here is a list of some of the directories created under containers directory showing permissions. Not sure if that provides any clues:

<pre>
[CMBL1291628b1:talk-jenkins-jobdsl/.containers/demo-1-8081] dlethin% find . -type d -maxdepth 4 | xargs ls -ld
drwxrwxrwx    4 dlethin  CORP\Domain Users   136 Feb 24 09:46 .
drwxrwxrwx   11 dlethin  CORP\Domain Users   374 Feb 24 09:52 ./jenkins-home
drwxr-xr-x    3 dlethin  CORP\Domain Users   102 Feb 24 09:47 ./jenkins-home/.java
drwxr-xr-x    3 dlethin  CORP\Domain Users   102 Feb 24 09:47 ./jenkins-home/.java/fonts
drwxr-xr-x    3 dlethin  CORP\Domain Users   102 Feb 24 09:47 ./jenkins-home/.java/fonts/1.7.0_65
drwxr-xr-x    3 dlethin  CORP\Domain Users   102 Feb 24 09:47 ./jenkins-home/init.groovy.d
drwxrwxrwx    3 dlethin  CORP\Domain Users   102 Feb 24 09:46 ./jenkins-home/jobs
drwxrwxrwx    3 dlethin  CORP\Domain Users   102 Feb 24 09:46 ./jenkins-home/jobs/Seed
drwxrwxrwx  134 dlethin  CORP\Domain Users  4556 Feb 24 09:50 ./jenkins-home/plugins
drwxr-xr-x    5 dlethin  CORP\Domain Users   170 Feb 24 09:48 ./jenkins-home/plugins/ant
drwxr-xr-x    4 dlethin  CORP\Domain Users   136 Feb 20  2013 ./jenkins-home/plugins/ant/META-INF
drwxr-xr-x    4 dlethin  CORP\Domain Users   136 Feb 24 09:48 ./jenkins-home/plugins/ant/WEB-INF
drwxr-xr-x    5 dlethin  CORP\Domain Users   170 Feb 24 09:48 ./jenkins-home/plugins/antisamy-markup-formatter
drwxr-xr-x    4 dlethin  CORP\Domain Users   136 Jun 17  2014 ./jenkins-home/plugins/antisamy-markup-formatter/META-INF
drwxr-xr-x    4 dlethin  CORP\Domain Users   136 Jun 17  2014 ./jenkins-home/plugins/antisamy-markup-formatter/WEB-INF
drwxr-xr-x    7 dlethin  CORP\Domain Users   238 Feb 24 09:49 ./jenkins-home/plugins/credentials
drwxr-xr-x    4 dlethin  CORP\Domain Users   136 Oct 18 18:41 ./jenkins-home/plugins/credentials/META-INF
drwxr-xr-x    4 dlethin  CORP\Domain Users   136 Oct 18 18:41 ./jenkins-home/plugins/credentials/WEB-INF
drwxr-xr-x    3 dlethin  CORP\Domain Users   102 Oct 18 18:41 ./jenkins-home/plugins/credentials/help
drwxr-xr-x    6 dlethin  CORP\Domain Users   204 Feb 24 09:48 ./jenkins-home/plugins/credentials/images
drwxr-xr-x    5 dlethin  CORP\Domain Users   170 Feb 24 09:50 ./jenkins-home/plugins/cvs
drwxr-xr-x    4 dlethin  CORP\Domain Users   136 Feb 24 09:49 ./jenkins-home/plugins/cvs/META-INF
drwxr-xr-x    4 dlethin  CORP\Domain Users   136 Feb 24 09:49 ./jenkins-home/plugins/cvs/WEB-INF
drwxr-xr-x    5 dlethin  CORP\Domain Users   170 Feb 24 09:50 ./jenkins-home/plugins/external-monitor-job
drwxr-xr-x    4 dlethin  CORP\Domain Users   136 Nov 18 06:32 ./jenkins-home/plugins/external-monitor-job/META-INF
drwxr-xr-x    4 dlethin  CORP\Domain Users   136 Feb 24 09:50 ./jenkins-home/plugins/external-monitor-job/WEB-INF
drwxr-xr-x    5 dlethin  CORP\Domain Users   170 Feb 24 09:50 ./jenkins-home/plugins/javadoc
drwxr-xr-x    4 dlethin  CORP\Domain Users   136 Feb 20  2013 ./jenkins-home/plugins/javadoc/META-INF
drwxr-xr-x    4 dlethin  CORP\Domain Users   136 Feb 24 09:50 ./jenkins-home/plugins/javadoc/WEB-INF
drwxr-xr-x    5 dlethin  CORP\Domain Users   170 Feb 24 09:50 ./jenkins-home/plugins/junit
drwxr-xr-x    4 dlethin  CORP\Domain Users   136 Nov  4 09:54 ./jenkins-home/plugins/junit/META-INF
drwxr-xr-x    4 dlethin  CORP\Domain Users   136 Nov  4 09:54 ./jenkins-home/plugins/junit/WEB-INF
drwxr-xr-x    8 dlethin  CORP\Domain Users   272 Feb 24 09:50 ./jenkins-home/plugins/ldap
drwxr-xr-x    4 dlethin  CORP\Domain Users   136 Jul 24  2013 ./jenkins-home/plugins/ldap/META-INF
drwxr-xr-x    4 dlethin  CORP\Domain Users   136 Feb 24 09:50 ./jenkins-home/plugins/ldap/WEB-INF
drwxr-xr-x    5 dlethin  CORP\Domain Users   170 Feb 24 09:50 ./jenkins-home/plugins/mailer
drwxr-xr-x    4 dlethin  CORP\Domain Users   136 Dec 17  2013 ./jenkins-home/plugins/mailer/META-INF
drwxr-xr-x    4 dlethin  CORP\Domain Users   136 Feb 24 09:50 ./jenkins-home/plugins/mailer/WEB-INF
drwxr-xr-x    5 dlethin  CORP\Domain Users   170 Feb 24 09:50 ./jenkins-home/plugins/matrix-auth
drwxr-xr-x    4 dlethin  CORP\Domain Users   136 Nov 11  2013 ./jenkins-home/plugins/matrix-auth/META-INF
drwxr-xr-x    4 dlethin  CORP\Domain Users   136 Feb 24 09:50 ./jenkins-home/plugins/matrix-auth/WEB-INF
drwxr-xr-x    6 dlethin  CORP\Domain Users   204 Feb 24 09:50 ./jenkins-home/plugins/matrix-project
drwxr-xr-x    4 dlethin  CORP\Domain Users   136 May  7  2014 ./jenkins-home/plugins/matrix-project/META-INF
drwxr-xr-x    4 dlethin  CORP\Domain Users   136 May  7  2014 ./jenkins-home/plugins/matrix-project/WEB-INF
drwxr-xr-x    3 dlethin  CORP\Domain Users   102 May  7  2014 ./jenkins-home/plugins/matrix-project/help
drwxr-xr-x   82 dlethin  CORP\Domain Users  2788 Feb 24 09:50 ./jenkins-home/plugins/maven-plugin
drwxr-xr-x    4 dlethin  CORP\Domain Users   136 Feb 24 09:50 ./jenkins-home/plugins/maven-plugin/META-INF
drwxr-xr-x    4 dlethin  CORP\Domain Users   136 Feb 24 09:50 ./jenkins-home/plugins/maven-plugin/WEB-INF
drwxr-xr-x    7 dlethin  CORP\Domain Users   238 Feb 24 09:47 ./jenkins-home/plugins/translation
drwxr-xr-x    4 dlethin  CORP\Domain Users   136 Nov  6  2012 ./jenkins-home/plugins/translation/META-INF
drwxr-xr-x    4 dlethin  CORP\Domain Users   136 Feb 24 09:47 ./jenkins-home/plugins/translation/WEB-INF
drwxr-xr-x    5 dlethin  CORP\Domain Users   170 Feb 24 09:47 ./jenkins-home/plugins/windows-slaves
drwxr-xr-x    4 dlethin  CORP\Domain Users   136 Jan  3  2014 ./jenkins-home/plugins/windows-slaves/META-INF
drwxr-xr-x    4 dlethin  CORP\Domain Users   136 Jan  3  2014 ./jenkins-home/plugins/windows-slaves/WEB-INF
drwxr-xr-x   24 dlethin  CORP\Domain Users   816 Feb 24 09:47 ./jenkins-home/war
drwxr-xr-x    6 dlethin  CORP\Domain Users   204 Feb 24 09:47 ./jenkins-home/war/META-INF
drwxr-xr-x    3 dlethin  CORP\Domain Users   102 Feb 24 09:47 ./jenkins-home/war/META-INF/maven
drwxr-xr-x   15 dlethin  CORP\Domain Users   510 Feb 24 09:47 ./jenkins-home/war/WEB-INF
drwxr-xr-x    4 dlethin  CORP\Domain Users   136 Feb 24 09:47 ./jenkins-home/war/WEB-INF/classes
drwxr-xr-x  127 dlethin  CORP\Domain Users  4318 Feb 24 09:47 ./jenkins-home/war/WEB-INF/lib
drwxr-xr-x   20 dlethin  CORP\Domain Users   680 Feb 24 09:47 ./jenkins-home/war/WEB-INF/plugins
drwxr-xr-x    4 dlethin  CORP\Domain Users   136 Feb 24 09:47 ./jenkins-home/war/WEB-INF/security
drwxr-xr-x    6 dlethin  CORP\Domain Users   204 Feb 24 09:47 ./jenkins-home/war/WEB-INF/update-center-rootCAs
drwxr-xr-x    5 dlethin  CORP\Domain Users   170 Feb 24 09:47 ./jenkins-home/war/css
drwxr-xr-x    3 dlethin  CORP\Domain Users   102 Feb 24 09:47 ./jenkins-home/war/executable
drwxr-xr-x   12 dlethin  CORP\Domain Users   408 Feb 24 09:47 ./jenkins-home/war/help
drwxr-xr-x   12 dlethin  CORP\Domain Users   408 Feb 24 09:47 ./jenkins-home/war/help/LogRecorder
drwxr-xr-x   63 dlethin  CORP\Domain Users  2142 Feb 24 09:47 ./jenkins-home/war/help/parameter
drwxr-xr-x   78 dlethin  CORP\Domain Users  2652 Feb 24 09:47 ./jenkins-home/war/help/project-config
drwxr-xr-x   10 dlethin  CORP\Domain Users   340 Feb 24 09:47 ./jenkins-home/war/help/run-config
drwxr-xr-x    6 dlethin  CORP\Domain Users   204 Feb 24 09:47 ./jenkins-home/war/help/scm-browsers
drwxr-xr-x   48 dlethin  CORP\Domain Users  1632 Feb 24 09:47 ./jenkins-home/war/help/system-config
drwxr-xr-x    3 dlethin  CORP\Domain Users   102 Feb 24 09:47 ./jenkins-home/war/help/tasks
drwxr-xr-x   13 dlethin  CORP\Domain Users   442 Feb 24 09:47 ./jenkins-home/war/help/tools
drwxr-xr-x   20 dlethin  CORP\Domain Users   680 Feb 24 09:47 ./jenkins-home/war/help/user
drwxr-xr-x   31 dlethin  CORP\Domain Users  1054 Feb 24 09:47 ./jenkins-home/war/help/view-config
drwxr-xr-x   30 dlethin  CORP\Domain Users  1020 Feb 24 09:47 ./jenkins-home/war/images
drwxr-xr-x  112 dlethin  CORP\Domain Users  3808 Feb 24 09:47 ./jenkins-home/war/images/16x16
drwxr-xr-x  116 dlethin  CORP\Domain Users  3944 Feb 24 09:47 ./jenkins-home/war/images/24x24
drwxr-xr-x   70 dlethin  CORP\Domain Users  2380 Feb 24 09:47 ./jenkins-home/war/images/32x32
drwxr-xr-x   99 dlethin  CORP\Domain Users  3366 Feb 24 09:47 ./jenkins-home/war/images/48x48
drwxr-xr-x   12 dlethin  CORP\Domain Users   408 Feb 24 09:47 ./jenkins-home/war/scripts
drwxr-xr-x   25 dlethin  CORP\Domain Users   850 Feb 24 09:47 ./jenkins-home/war/scripts/yui
drwxrwxrwx    2 dlethin  CORP\Domain Users    68 Feb 24 09:46 ./jenkins-root
</pre>

**Comment by pvdissel** [comment] 2015-02-24 17:43
The directory structure looks fine to me.
What you could do is, empty the `plugin-urls.txt` file, this way only the default provided Jenkins plugins will be loaded. Will Jenkins start with that?

**Comment by dlethin** [comment] 2015-02-24 17:52
I had a small amount of success, which seems to narrow down where my problem is.

I commented out the following line from the jenkins script:

<pre>
function start() {
    local projectPath="$1"
    local volumes=("${jenkinsDir}:/var/jenkins_home")
    # commenting this out -- is problem specific to jenkins_root?
    #volumes+=("${jenkinsUserHomeDir}:/root")
</pre>

And sure enough after doing that, things proceeded to work.  Jenkins got past where it was hanging, the script was able to detect it is up and execute the seed job, and the seed job properly run and populated the jenkins jobs.

What am I missing by not mounting /root volumen from jenkins_root under containers folder?

In the meantime, I've gotten some feedback from local developer here that boot2docker is a big pain in the A and he recommends altneratives to spinning up a linux host with a docker container, including perhaps using Vagrant which now has support for docker.   I'll consider exploring that.

In light of my new findings, if deleting plugin-urls.txt of any use to continue?

**Comment by pvdissel** [comment] 2015-02-24 18:08
> What am I missing by not mounting /root volumen from jenkins_root under containers folder?

I don't think you're missing anything without the /root mounted. Originally the idea was to be able to put additional ssh keys in there, but so far I haven't needed it.

> In light of my new findings, if deleting plugin-urls.txt of any use to continue?

I don't think so. As you say, it all works if you skip the /root mounting.

I've applied the fixed of, not using `sudo` when boot2docker is available and not mounting `/root`, to master. So you and hopefully other OSX users can enjoy the script.
Thanks for the issue and help working towards a solution. With this, can we close this issue?

**Comment by dlethin** [comment] 2015-02-24 18:58
While I had some success as reported earlier, I can't get this to repeatedly work consistently.  I did _something_ to get demo1 to work, but then tried to get demo2 working and ran into the same problem.

Then I moved my .containers directory to .containers.bak, did a git pull to get your changes and tried to run demo1 again (which had been working), but ran into the same issue -- staling when starting up java.

The only other thing I played around with was at one point removing the "-u root" option from the docker run command.

So I'm back to this not working and scratching my head.  I'm running out of things to try. Getting this to work on OSX would be nice, and its a good learning exercise for me, but it's starting to take a bit long but I'm mostly interested in the meet of what your seed jobs are doing so.

Not sure what the priority is for you to have these demos working on OSX.  I'd be happy to help if you have other suggestions.  You mentioned there might be an OSX resource on your team that can try things out?

Cheers.

**Comment by pvdissel** [comment] 2015-02-24 19:03
Hmm.. ok, I wil try to get this working on a Mac, Thursday when I'm back at work

**Comment by pvdissel** [comment] 2015-02-26 15:52
Will be monday before I can test it on a Mac, the Mac using collegue is off until then

**Comment by dlethin** [comment] 2015-03-01 15:38
OK, I found some time some this morning to focus and play around with this without interruption and discovered that the issue appears to be that I am just impatient :-(     It looks like everything works, even if I uncomment the following line:

<pre>
# if you want to add/edit the files in /root of the jenkins container
# uncomment the line below:
    volumes+=("${jenkinsUserHomeDir}:/root")
</pre>

It appears the issue I'm having is that starting up jenkins for the first time is just darn slow.  It take 12 minutes between the "Starting initialization" message and the next message, "Listing all plugins"

<pre>
...
INFO: NO JSP Support for , did not find org.apache.jasper.servlet.JspServlet
Jenkins home directory: /var/jenkins_home found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
Mar 01, 2015 3:04:40 PM org.eclipse.jetty.util.log.JavaUtilLog info
INFO: Started SelectChannelConnector@0.0.0.0:8080
Mar 01, 2015 3:04:40 PM winstone.Logger logInternal
INFO: Winstone Servlet Engine v2.0 running: controlPort=disabled
Mar 01, 2015 3:04:41 PM jenkins.InitReactorRunner$1 onAttained
INFO: Started initialization
Mar 01, 2015 3:16:46 PM jenkins.InitReactorRunner$1 onAttained
INFO: Listed all plugins
...
</pre>

But it eventually does start up.  Along the way in troubleshooting this, I learned a lot about docker which is helpful to me.  I learned how to use docker exec to open a bash shell in the container.  This way I could kill -QUIT the jenkins jvm process and see the stack trace.  There was able to verify that things weren't hung.. they were just slow.

I would guess the issue is that there are performance issues with the underlying implementation of how boot2docker and or virtualbox are doing the shared mounts.

One theory a collegue proposed to me earlier in the week was to not use boot2docker but instead use Vagrant, and if I were to do that, vagrant has options for sharing volumes over nfs which is known to improve performance.

The only other feedback I can add regarding docker is that the stopDemos script as written does not work.  The issue is that it assumes the container names end with 8080, which is not the case, as each demo is started in startDemos with its own dedicated port #.

<pre>
bash-3.2$ docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS                               NAMES
98c529f9c0c4        jenkins:1.580.2     "/usr/local/bin/jenk   31 minutes ago      Up 30 minutes       50000/tcp, 0.0.0.0:8081->8080/tcp   demo-1-8081         
bash-3.2$ ./stopDemos 
Stopping container [demo-1-8080]...
Stopped container [demo-1-8080]
Stopping container [demo-2-8080]...
Stopped container [demo-2-8080]
Stopping container [demo-3-8080]...
Stopped container [demo-3-8080]
Stopping container [demo-4-8080]...
Stopped container [demo-4-8080]
Stopping container [demo-5-8080]...
Stopped container [demo-5-8080]
bash-3.2$ docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS                               NAMES
98c529f9c0c4        jenkins:1.580.2     "/usr/local/bin/jenk   32 minutes ago      Up 32 minutes       50000/tcp, 0.0.0.0:8081->8080/tcp   demo-1-8081  
</pre>

Thanks again for all your help on this. I'm going to try sometime in the next day or so to troubleshoot why I'm having trouble running demo 04 via gradle locally and not in a container as I reported in issue #3 

Cheers.

Doug

**Comment by pvdissel** [comment] 2015-03-01 15:47
Hey Doug, that's very good to hear :smile: 
I will improve the jenkins script by adding a message about the possible boot2docker mount slowness, so atleast others know whats going on.

About stopDemos, I'll see what I can do there.

Thanks for the great investigation and feedback.
With this, closing this issue.

**Closed as completed by pvdissel** 2015-03-01 15:47 UTC
